# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42363c8d9e380931cc08760b4ee644c1460c527abb94876398d8cd8ac7460d883408cd8316ef9c9d3850dd2d5a24d0b8b458d15c15b55a9f81774b1f4c803580

test:
  secret_key_base: b1d1902f7c3c3c003f4cc3a2a4ef0d67af7e0a7c6084cf71d907bbf7b88de2ae8794774056698fd2626240881166cdb9220ce8d9ce36ec03fd514a9c531fbfd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
